feat(overdue-balance): add doc guide for overdue balance display
getlago/lago-doc pull request #167
Opened 2024-07-08 14:27 UTC by AlexEven

* Guide for overdue balance display
* Updated screenshots for the customer section, whose layout has evolved

To be merged **when ftr-overdue-balance is released**, later this week 🙏

Thanks!

2024-07-08 14:45 UTC, rsempe requested changes

2024-07-08 14:45 UTC, rsempe commented on guide/analytics/invoice-overdue.mdx
> +    ```bash Get MRR
```suggestion
    ```bash Get Overdue balance
```

2024-07-08 14:45 UTC, rsempe commented on guide/analytics/invoice-overdue.mdx
> +    curl --location --request GET "$LAGO_URL/api/v1/analytics/overdue_balances?currency=USD" \
```suggestion
    curl --location --request GET "$LAGO_URL/api/v1/analytics/overdue_balance?currency=USD" \
```

2024-07-08 14:46 UTC, sarkissianraffi approved these changes

2024-07-12 09:12 UTC, rsempe approved these changes

2024-07-12 09:13 UTC, rsempe commented
Screenshot [guide/analytics/images/overdue-invoices.png](https://github.com/getlago/lago-doc/pull/167/files#diff-7d2c74b9a390d02dd5a7aa571c8088130e3917213fe53200637a30ca08eb2215) is not correct with the wording change, no?

2024-07-12 15:05 UTC, merged