feat(dunning): add overdue balance manual payment
getlago/lago-doc pull request #198
Opened 2024-09-13 09:34 UTC by AlexEven

Not to be merged for now, waiting full cloud release. Thank you!

@rsempe - if you can validate the API part 🙏

2024-09-13 09:53 UTC, rsempe approved these changes

2024-09-14 09:56 UTC, michaelponrajah requested changes
As we introduce a new endpoint, we should reference it in the API ref.  
`POST /payment_requests/`

2024-09-17 14:09 UTC, AlexEven commented
@michaelponrajah I added the API ref, can you please check and merge if all good to you? 
Thank you!

2024-09-19 10:06 UTC, michaelponrajah approved these changes

2024-09-19 10:06 UTC, michaelponrajah commented on api-reference/payment-requests/payment-request-object.mdx
> +title: "The paymentrequest object"
Missing space between payment and request

2024-09-19 10:15 UTC, michaelponrajah approved these changes

2024-09-19 13:02 UTC, merged