doc(taxes): add taxes info in other section
getlago/lago-doc pull request #6
Opened 2023-07-07 20:05 UTC by michaelponrajah

## Description

Add taxes in other section of the guide

2023-07-07 20:08 UTC, ansmonjol approved these changes

2023-07-10 20:10 UTC, sarkissianraffi requested changes

2023-07-10 20:10 UTC, sarkissianraffi commented on guide/invoicing/download-invoices.mdx
Is this an empty string? @michaelponrajah

2023-07-10 20:10 UTC, sarkissianraffi commented on api-reference/taxes/create.mdx
> +		name="TVA",
extra space here @michaelponrajah

2023-07-10 20:10 UTC, sarkissianraffi commented on api-reference/taxes/create.mdx
> +	name: "TVA",
Same extra space @michaelponrajah

2023-07-10 20:10 UTC, sarkissianraffi commented on api-reference/taxes/object.mdx
> +    <ResponseField name="description" type="string | null">
same

2023-07-10 20:10 UTC, sarkissianraffi commented on api-reference/taxes/object.mdx
> +    <ResponseField name="applied_to_organization" type="boolean required">
bad closing for type @michaelponrajah

2023-07-10 20:10 UTC, sarkissianraffi commented on api-reference/taxes/object.mdx
> +title: "The billable metric object"
Bad title @michaelponrajah

2023-07-11 13:04 UTC, merged